version: "3.8"
services:
  db:
    image: mysql
    container_name: "MySQL_COVID"
    ports:
      - 32000:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=passwel
      - MYSQL_HOST=db
    volumes: # map local to container
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    depends_on:
      - db
    build: ./app
    container_name: "Python_app"
    links:
      - db
    ports:
      - 5000:5000

  metabase:
    image: metabase/metabase
    container_name: "metabase_covid"
    depends_on:
      - db
    ports:
      - '4000:3000'
    volumes:
      - ./metabase:/metabase-data/metabase.db
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_HOST=db
      - MB_DB_DBNAME=covid
      - MB_DB_PORT=3306
      - MB_DB_USER=root
      - MB_DB_PASS=passwel
